name: validate

on:
  pull_request:

jobs:
  regopy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install regopy
        run: python -m pip install regopy==1.4.0 --break-system-packages
      - name: Run policy tests
        run: python test/run_tests.py
